name: Daily Summary Bot

on:
  schedule:
    - cron: "0 13 * * *"  # 9:00 AM ET
    - cron: "0 21 * * *"  # 5:00 PM ET
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set summary label
        id: summary
        run: |
          if [ "$(date -u +'%H')" = "13" ]; then
            echo "label=(Morning)" >> $GITHUB_OUTPUT
          else
            echo "label=(Evening)" >> $GITHUB_OUTPUT
          fi

      - name: Run bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SUMMARY_LABEL: ${{ steps.summary.outputs.label }}
        run: python main.py