name: Daily Insider Bot

on:
  schedule:
    - cron: '0 12,21 * * *'  # 8 AM and 5 PM ET (12, 21 UTC)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      SUMMARY_LABEL: ${{ github.event_name == 'schedule' && (github.event.schedule == '0 12 * * *' && '(Morning)' || '(Evening)') || '(Manual)' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # ✅ FIXED VERSION

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run insider flow bot
        run: python main.py