name: Daily Insider Summary

on:
  workflow_dispatch: {}  # Manual trigger for testing
  schedule:
    - cron: '30 12 * * *'  # Runs every day at 12:30 UTC (8:30 AM ET)

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          COMPANY_NAME: ${{ secrets.COMPANY_NAME }}
          SEC_EMAIL: ${{ secrets.SEC_EMAIL }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SUMMARY_LABEL: "Morning"
        run: python main.py