name: Daily Insider Bot

on:
  schedule:
    # Runs at 8:00 AM and 5:00 PM ET → 12:00 and 21:00 UTC
    - cron: '0 12,21 * * *'
  workflow_dispatch:  # allows you to run it manually

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      SUMMARY_LABEL: ${{ github.event_name == 'schedule' && (github.event.schedule == '0 12 * * *' && '(Morning)' || '(Evening)') || '(Manual)' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run insider flow bot
        run: python main.py